if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'CLAIMSRATE'
'COMPENSATION'
'CUSTOMERAGE'
'CUSTOMERMONETARYVALUE'
'EDUCATIONALDEGREE'
'FIRSTPOLICYYEAR'
'GEOGRAPHICLIVINGAREA'
'GROSSMONTHLYSALARY'
'HASCHILDREN'
'HEALTH'
'HOUSEHOLD'
'LIFE'
'MOTOR'
) then ROLE='INPUT';
else delete;
end;
