data TextFilter_terms;
  length   KEY                                  8
           Term                             $ 256
           Role                             $ 256
           WEIGHT                               8
           KEEP                             $   1
           PARENT                               8
           _ISPAR                           $   1
           ;
 
  label    Term="Term"
           ;
KEY=1; Term="symphony"; Role="Noun"; WEIGHT=0.49380985937635; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=4; Term="minor"; Role="Prop"; WEIGHT=0.48608094404615; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=5; Term="op"; Role="Prop"; WEIGHT=0.38368939201102; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=6; Term="ii"; Role="Prop"; WEIGHT=0.51079899130983; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=7; Term="allegro"; Role="Noun"; WEIGHT=0.67680027592654; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=8; Term="fs"; Role="Prop"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=9; Term="adagio"; Role="Noun"; WEIGHT=0.64777707933295; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=11; Term="blue"; Role="Noun"; WEIGHT=0.63149771798537; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=13; Term="waltz"; Role="Noun"; WEIGHT=0.72953715079995; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=16; Term="feat"; Role="Noun"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=22; Term="cavalleria"; Role="Prop"; WEIGHT=0.71421768411982; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=27; Term="mama"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=39; Term="violin"; Role="Noun"; WEIGHT=0.62406340105313; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=40; Term="concerto"; Role="Prop"; WEIGHT=0.61035967113968; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=41; Term="allegro"; Role="Adj"; WEIGHT=0.56363308180405; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=42; Term="molto"; Role="Adv"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=44; Term="la"; Role="Noun"; WEIGHT=0.59415884978208; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=46; Term="dance"; Role="Noun"; WEIGHT=0.60401377174808; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=51; Term="suite"; Role="Noun"; WEIGHT=0.66638951017951; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=54; Term="allegretto"; Role="Noun"; WEIGHT=0.72953715079995; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=55; Term="concerto"; Role="Noun"; WEIGHT=0.63149771798537; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=56; Term="grosso"; Role="Prop"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=58; Term="major"; Role="Prop"; WEIGHT=0.53390911798645; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=60; Term="iii"; Role="Prop"; WEIGHT=0.54922858466659; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=61; Term="clair"; Role="Prop"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=71; Term="song"; Role="Noun"; WEIGHT=0.65979765040851; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=73; Term="tale"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=76; Term="flight"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=79; Term="major"; Role="Noun"; WEIGHT=0.68811742260354; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=80; Term="le"; Role="Prop"; WEIGHT=0.73425196924574; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=105; Term="le"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=109; Term="string"; Role="Adj"; WEIGHT=0.70051395420636; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=110; Term="quartet"; Role="Noun"; WEIGHT=0.71421768411982; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=111; Term="hob"; Role="Noun"; WEIGHT=0.72953715079995; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=118; Term="rondo"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=124; Term="overture"; Role="Noun"; WEIGHT=0.64777707933295; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=125; Term="finale"; Role="Noun"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=128; Term="rusticana"; Role="Prop"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=135; Term="scheherazade"; Role="Prop"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=136; Term="young"; Role="Prop"; WEIGHT=0.79842166286913; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=137; Term="prince"; Role="Noun"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=138; Term="princess"; Role="Noun"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=141; Term="battle"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=157; Term="sostenuto"; Role="Noun"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=158; Term="die"; Role="Noun"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=164; Term="rhapsody"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=168; Term="iv"; Role="Prop"; WEIGHT=0.65675064662149; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=184; Term="act"; Role="Noun"; WEIGHT=0.70051395420636; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=191; Term="troppo"; Role="Adv"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=196; Term="air"; Role="Noun"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=199; Term="prelude"; Role="Noun"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=203; Term="sonata"; Role="Noun"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=210; Term="orchestra"; Role="Noun"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=214; Term="spring"; Role="Prop"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=222; Term="sonata"; Role="Prop"; WEIGHT=0.66638951017951; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=225; Term="andante"; Role="Noun"; WEIGHT=0.68811742260354; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=234; Term="march"; Role="Noun"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=236; Term="piano concerto"; Role="NOUN_GROUP"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=237; Term="piano"; Role="Adj"; WEIGHT=0.67680027592654; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=257; Term="la"; Role="Prop"; WEIGHT=0.79842166286913; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=267; Term="music"; Role="Noun"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=270; Term="blue"; Role="Prop"; WEIGHT=0.72953715079995; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=299; Term="keyboard"; Role="Noun"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=301; Term="der"; Role="Prop"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=307; Term="girl"; Role="Noun"; WEIGHT=0.66638951017951; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=319; Term="adagietto"; Role="Prop"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=340; Term="e-flat"; Role="Prop"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=345; Term="toccata"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=348; Term="tales"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=73; _ISPAR=".";
output;
KEY=379; Term="cello"; Role="Noun"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=404; Term="moderato"; Role="Adj"; WEIGHT=0.71421768411982; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=415; Term="ave"; Role="Noun"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=416; Term="maria"; Role="Prop"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=438; Term="hungarian dance"; Role="NOUN_GROUP"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=439; Term="hungarian"; Role="Adj"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=452; Term="airs"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=196; _ISPAR=".";
output;
KEY=453; Term="dances"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=46; _ISPAR=".";
output;
KEY=458; Term="wab"; Role="Prop"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=475; Term="con"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=487; Term="minor"; Role="Noun"; WEIGHT=0.70051395420636; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=505; Term="mountain"; Role="Noun"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=527; Term="night"; Role="Noun"; WEIGHT=0.62406340105313; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=539; Term="du"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=547; Term="angel"; Role="Noun"; WEIGHT=0.72953715079995; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=586; Term="flowers"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=1044; _ISPAR=".";
output;
KEY=590; Term="digital"; Role="Prop"; WEIGHT=0.61703114050626; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=591; Term="remaster"; Role="Prop"; WEIGHT=0.56203220623271; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=595; Term="b-flat"; Role="Prop"; WEIGHT=0.72953715079995; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=603; Term="dies"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=158; _ISPAR=".";
output;
KEY=606; Term="sharp"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=610; Term="old"; Role="Adj"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=617; Term="bringer"; Role="Prop"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=632; Term="vivace"; Role="Adj"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=635; Term="god"; Role="Noun"; WEIGHT=0.71421768411982; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=662; Term="river"; Role="Noun"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=675; Term="world"; Role="Noun"; WEIGHT=0.61035967113968; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=680; Term="fire"; Role="Noun"; WEIGHT=0.71421768411982; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=704; Term="planets"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=2427; _ISPAR=".";
output;
KEY=711; Term="una"; Role="Prop"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=721; Term="king"; Role="Noun"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=846; Term="man"; Role="Noun"; WEIGHT=0.66638951017951; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=863; Term="rite"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=882; Term="love"; Role="Noun"; WEIGHT=0.46531862727522; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=900; Term="songs"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=71; _ISPAR=".";
output;
KEY=933; Term="round"; Role="Prop"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=954; Term="breathe"; Role="Verb"; WEIGHT=0.82672995049971; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=960; Term="money"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=963; Term="bad"; Role="Adj"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=968; Term="band"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=971; Term="catch"; Role="Verb"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=975; Term="eyes"; Role="Prop"; WEIGHT=0.71421768411982; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=978; Term="boy"; Role="Noun"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=980; Term="alone"; Role="Adv"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=983; Term="road"; Role="Noun"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=997; Term="back"; Role="Adv"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1011; Term="love"; Role="Prop"; WEIGHT=0.65675064662149; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1016; Term="rock"; Role="Noun"; WEIGHT=0.67680027592654; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=1028; Term="life"; Role="Noun"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1036; Term="want"; Role="Verb"; WEIGHT=0.69412928958465; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=1043; Term="wild"; Role="Adj"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=1044; Term="flower"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=1051; Term="big"; Role="Adj"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1052; Term="live"; Role="Verb"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1070; Term="broken"; Role="Adj"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1071; Term="dreams"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=1442; _ISPAR=".";
output;
KEY=1072; Term="train"; Role="Noun"; WEIGHT=0.77266329627865; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1080; Term="sun"; Role="Noun"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1083; Term="bells"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=2491; _ISPAR=".";
output;
KEY=1085; Term="fall"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1086; Term="down"; Role="Prop"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1089; Term="lovin"; Role="Prop"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1107; Term="heart"; Role="Noun"; WEIGHT=0.63938286773327; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1121; Term="little"; Role="Adj"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=1122; Term="things"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=1241; _ISPAR=".";
output;
KEY=1123; Term="hell"; Role="Noun"; WEIGHT=0.65675064662149; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1133; Term="down"; Role="Adv"; WEIGHT=0.71421768411982; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1142; Term="last"; Role="Prop"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1148; Term="black"; Role="Adj"; WEIGHT=0.71421768411982; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1152; Term="boys"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=978; _ISPAR=".";
output;
KEY=1153; Term="back"; Role="Prop"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1168; Term="remember"; Role="Verb"; WEIGHT=0.71421768411982; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1169; Term="know"; Role="Verb"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1171; Term="feels"; Role="Verb"; WEIGHT=0; KEEP="Y"; PARENT=1330; _ISPAR=".";
output;
KEY=1176; Term="surrender"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1183; Term="dark"; Role="Adj"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1188; Term="smoke"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1196; Term="version"; Role="Noun"; WEIGHT=0.72953715079995; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1208; Term="roll"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1237; Term="lady"; Role="Noun"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1238; Term="black"; Role="Noun"; WEIGHT=0.68811742260354; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1241; Term="thing"; Role="Noun"; WEIGHT=0.65675064662149; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=1243; Term="hot"; Role="Adj"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1246; Term="easy"; Role="Adj"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1270; Term="ain't"; Role="Prop"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1284; Term="wanna"; Role="Prop"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1287; Term="open"; Role="Adj"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1291; Term="edge"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1293; Term="baby"; Role="Noun"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=1300; Term="heaven"; Role="Noun"; WEIGHT=0.67680027592654; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1304; Term="death"; Role="Noun"; WEIGHT=0.71421768411982; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1308; Term="face"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1310; Term="hard"; Role="Adj"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1326; Term="kind"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1330; Term="feel"; Role="Verb"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=1332; Term="kill"; Role="Verb"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=1349; Term="body"; Role="Noun"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1366; Term="rain"; Role="Noun"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1387; Term="gotta"; Role="Prop"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1394; Term="sweet"; Role="Adj"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1395; Term="child"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=1424; Term="blood"; Role="Noun"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1431; Term="american"; Role="Adj"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1442; Term="dream"; Role="Noun"; WEIGHT=0.68811742260354; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=1470; Term="blue"; Role="Adj"; WEIGHT=0.71421768411982; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1471; Term="eyes"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=2429; _ISPAR=".";
output;
KEY=1478; Term="heavy"; Role="Adj"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1479; Term="metal"; Role="Noun"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1480; Term="time"; Role="Noun"; WEIGHT=0.66962982991673; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=1486; Term="day"; Role="Noun"; WEIGHT=0.66638951017951; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=1490; Term="dead"; Role="Prop"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1511; Term="wants"; Role="Verb"; WEIGHT=0; KEEP="Y"; PARENT=1036; _ISPAR=".";
output;
KEY=1538; Term="die"; Role="Verb"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1543; Term="blues"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=11; _ISPAR=".";
output;
KEY=1548; Term="home"; Role="Noun"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1556; Term="right"; Role="Noun"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1561; Term="days"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=1486; _ISPAR=".";
output;
KEY=1585; Term="warrior"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=1594; Term="soul"; Role="Noun"; WEIGHT=0.72953715079995; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=1651; Term="babies"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=1293; _ISPAR=".";
output;
KEY=1669; Term="good"; Role="Adj"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1751; Term="littlest"; Role="Adj"; WEIGHT=0; KEEP="Y"; PARENT=1121; _ISPAR=".";
output;
KEY=1773; Term="shine"; Role="Noun"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1818; Term="stars"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=2856; _ISPAR=".";
output;
KEY=1833; Term="beautiful"; Role="Adj"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1865; Term="wildest"; Role="Adj"; WEIGHT=0; KEEP="Y"; PARENT=1043; _ISPAR=".";
output;
KEY=1938; Term="hands"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=2049; _ISPAR=".";
output;
KEY=1990; Term="party"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=1991; Term="killed"; Role="Verb"; WEIGHT=0; KEEP="Y"; PARENT=1332; _ISPAR=".";
output;
KEY=2046; Term="girls"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=307; _ISPAR=".";
output;
KEY=2049; Term="hand"; Role="Noun"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=2070; Term="rocks"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=1016; _ISPAR=".";
output;
KEY=2082; Term="remastered"; Role="Prop"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=2121; Term="living"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=2132; Term="gods"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=635; _ISPAR=".";
output;
KEY=2138; Term="souls"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=1594; _ISPAR=".";
output;
KEY=2189; Term="times"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=1480; _ISPAR=".";
output;
KEY=2237; Term="electric"; Role="Adj"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=2415; Term="midnight"; Role="Prop"; WEIGHT=0.72953715079995; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=2427; Term="planet"; Role="Noun"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=2429; Term="eye"; Role="Noun"; WEIGHT=0.79066823727304; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=2448; Term="nights"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=527; _ISPAR=".";
output;
KEY=2449; Term="warriors"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=1585; _ISPAR=".";
output;
KEY=2491; Term="bell"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=2514; Term="caught"; Role="Verb"; WEIGHT=0; KEEP="Y"; PARENT=971; _ISPAR=".";
output;
KEY=2527; Term="rites"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=863; _ISPAR=".";
output;
KEY=2551; Term="men"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=846; _ISPAR=".";
output;
KEY=2596; Term="children"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=1395; _ISPAR=".";
output;
KEY=2658; Term="bands"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=968; _ISPAR=".";
output;
KEY=2677; Term="park"; Role="Noun"; WEIGHT=0.81969143386663; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=2701; Term="mood"; Role="Noun"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=2768; Term="blues"; Role="Prop"; WEIGHT=0.76695455899322; KEEP="Y"; PARENT=.; _ISPAR="";
output;
KEY=2828; Term="rivers"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=662; _ISPAR=".";
output;
KEY=2856; Term="star"; Role="Noun"; WEIGHT=0.74690492968817; KEEP="Y"; PARENT=.; _ISPAR="+";
output;
KEY=3069; Term="las"; Role="Noun"; WEIGHT=0; KEEP="Y"; PARENT=44; _ISPAR=".";
output;
;
run;
data TextFilter_multiwordterms;
  length   term                             $ 256
           role                             $ 256
           ;
 
term="A BIT"; role="Adv";
output;
term="A Bit"; role="Adv";
output;
term="A FORTIORI"; role="Adv";
output;
term="A Fortiori"; role="Adv";
output;
term="A LOT"; role="Adv";
output;
term="A LOT OF"; role="Adj";
output;
term="A Lot"; role="Adv";
output;
term="A Lot Of"; role="Adj";
output;
term="A POSTERIORI"; role="Adj";
output;
term="A POSTERIORI"; role="Adv";
output;
term="A PRIORI"; role="Adj";
output;
term="A PRIORI"; role="Adv";
output;
term="A Posteriori"; role="Adj";
output;
term="A Posteriori"; role="Adv";
output;
term="A Priori"; role="Adj";
output;
term="A Priori"; role="Adv";
output;
term="ACCORDING TO"; role="Prep";
output;
term="AD HOC"; role="Adj";
output;
term="AD INTERIM"; role="Adv";
output;
term="AHEAD OF"; role="Prep";
output;
term="ALL THE TIME"; role="Adv";
output;
term="ALONG WITH"; role="Prep";
output;
term="ANY MOMENT"; role="Adv";
output;
term="ANY SECOND"; role="Adv";
output;
term="APART FROM"; role="Prep";
output;
term="AS A RESULT OF"; role="Prep";
output;
term="AS A RULE"; role="Adv";
output;
term="AS FAR AS"; role="Conj";
output;
term="AS FAR AS"; role="Prep";
output;
term="AS FOR"; role="Prep";
output;
term="AS IF"; role="Conj";
output;
term="AS IN"; role="Prep";
output;
term="AS LONG AS"; role="Conj";
output;
term="AS MANY AS"; role="Adv";
output;
term="AS OF"; role="Prep";
output;
term="AS ONE"; role="Adv";
output;
term="AS PER"; role="Prep";
output;
term="AS REGARDS"; role="Prep";
output;
term="AS SOON AS"; role="Conj";
output;
term="AS THOUGH"; role="Conj";
output;
term="AS TO"; role="Prep";
output;
term="AS WELL"; role="Adv";
output;
term="AS WELL AS"; role="Conj";
output;
term="AS YET"; role="Adv";
output;
term="ASIDE FROM"; role="Prep";
output;
term="ASSUMING THAT"; role="Conj";
output;
term="AT ALL"; role="Adv";
output;
term="AT ANY RATE"; role="Adv";
output;
term="AT LEAST ONE"; role="Adj";
output;
term="AT ONCE"; role="Adv";
output;
term="AT THE EXPENSE OF"; role="Prep";
output;
term="AT VARIANCE WITH"; role="Prep";
output;
term="AWAY FROM"; role="Prep";
output;
term="According To"; role="Prep";
output;
term="Ad Hoc"; role="Adj";
output;
term="Ad Interim"; role="Adv";
output;
term="Ahead Of"; role="Prep";
output;
term="All The Time"; role="Adv";
output;
term="Along With"; role="Prep";
output;
term="Any Moment"; role="Adv";
output;
term="Any Second"; role="Adv";
output;
term="Apart From"; role="Prep";
output;
term="As A Result Of"; role="Prep";
output;
term="As A Rule"; role="Adv";
output;
term="As Far As"; role="Conj";
output;
term="As Far As"; role="Prep";
output;
term="As For"; role="Prep";
output;
term="As If"; role="Conj";
output;
term="As In"; role="Prep";
output;
term="As Long As"; role="Conj";
output;
term="As Many As"; role="Adv";
output;
term="As Of"; role="Prep";
output;
term="As One"; role="Adv";
output;
term="As Per"; role="Prep";
output;
term="As Regards"; role="Prep";
output;
term="As Soon As"; role="Conj";
output;
term="As Though"; role="Conj";
output;
term="As To"; role="Prep";
output;
term="As Well"; role="Adv";
output;
term="As Well As"; role="Conj";
output;
term="As Yet"; role="Adv";
output;
term="Aside From"; role="Prep";
output;
term="Assuming That"; role="Conj";
output;
term="At All"; role="Adv";
output;
term="At Any Rate"; role="Adv";
output;
term="At Least One"; role="Adj";
output;
term="At Once"; role="Adv";
output;
term="At The Expense Of"; role="Prep";
output;
term="At Variance With"; role="Prep";
output;
term="Away From"; role="Prep";
output;
term="BACK OF"; role="Prep";
output;
term="BEAR UP"; role="Verb";
output;
term="BECAUSE OF"; role="Prep";
output;
term="BEST KNOWN"; role="Adj";
output;
term="BLACK AND WHITE"; role="Adj";
output;
term="BONA FIDE"; role="Adj";
output;
term="BREAK UP"; role="Verb";
output;
term="BRING ABOUT"; role="Verb";
output;
term="BRING UP"; role="Verb";
output;
term="BUILD UP"; role="Verb";
output;
term="BUT FOR"; role="Prep";
output;
term="BY DINT OF"; role="Prep";
output;
term="BY ITSELF"; role="Adv";
output;
term="BY MEANS OF"; role="Prep";
output;
term="BY PROXY"; role="Adv";
output;
term="BY REASON OF"; role="Prep";
output;
term="BY THE WAY"; role="Adv";
output;
term="BY VIRTUE OF"; role="Prep";
output;
term="BY WAY OF"; role="Prep";
output;
term="Back Of"; role="Prep";
output;
term="Bear Up"; role="Verb";
output;
term="Because Of"; role="Prep";
output;
term="Best Known"; role="Adj";
output;
term="Black And White"; role="Adj";
output;
term="Bona Fide"; role="Adj";
output;
term="Break Up"; role="Verb";
output;
term="Bring About"; role="Verb";
output;
term="Bring Up"; role="Verb";
output;
term="Build Up"; role="Verb";
output;
term="But For"; role="Prep";
output;
term="By Dint Of"; role="Prep";
output;
term="By Itself"; role="Adv";
output;
term="By Means Of"; role="Prep";
output;
term="By Proxy"; role="Adv";
output;
term="By Reason Of"; role="Prep";
output;
term="By The Way"; role="Adv";
output;
term="By Virtue Of"; role="Prep";
output;
term="By Way Of"; role="Prep";
output;
term="CARRY ON"; role="Verb";
output;
term="CARRY OUT"; role="Verb";
output;
term="CARRY THROUGH"; role="Verb";
output;
term="CATCH ON"; role="Verb";
output;
term="CENTRAL AFRICAN"; role="Adj";
output;
term="CLEAN UP"; role="Verb";
output;
term="CLEAR UP"; role="Verb";
output;
term="CLOSE BY"; role="Adv";
output;
term="CLOSE TO"; role="Adv";
output;
term="COME ABOUT"; role="Verb";
output;
term="COME IN"; role="Verb";
output;
term="COME ON"; role="Verb";
output;
term="CONSIDERING THAT"; role="Conj";
output;
term="COSTA RICAN"; role="Adj";
output;
term="COVER UP"; role="Verb";
output;
term="CUT OFF"; role="Verb";
output;
term="Carry On"; role="Verb";
output;
term="Carry Out"; role="Verb";
output;
term="Carry Through"; role="Verb";
output;
term="Catch On"; role="Verb";
output;
term="Central African"; role="Adj";
output;
term="Clean Up"; role="Verb";
output;
term="Clear Up"; role="Verb";
output;
term="Close By"; role="Adv";
output;
term="Close To"; role="Adv";
output;
term="Come About"; role="Verb";
output;
term="Come In"; role="Verb";
output;
term="Come On"; role="Verb";
output;
term="Considering That"; role="Conj";
output;
term="Costa Rican"; role="Adj";
output;
term="Cover Up"; role="Verb";
output;
term="Cut Off"; role="Verb";
output;
term="DARE TO"; role="Aux";
output;
term="DARK BLUE"; role="Adj";
output;
term="DE FACTO"; role="Adj";
output;
term="DE FACTO"; role="Adv";
output;
term="DE JURE"; role="Adj";
output;
term="DE JURE"; role="Adv";
output;
term="DEVOID OF"; role="Prep";
output;
term="DRAW DOWN"; role="Verb";
output;
term="DUE TO"; role="Prep";
output;
term="Dare To"; role="Aux";
output;
term="Dark Blue"; role="Adj";
output;
term="De Facto"; role="Adj";
output;
term="De Facto"; role="Adv";
output;
term="De Jure"; role="Adj";
output;
term="De Jure"; role="Adv";
output;
term="Devoid Of"; role="Prep";
output;
term="Draw Down"; role="Verb";
output;
term="Due To"; role="Prep";
output;
term="EAST GERMAN"; role="Adj";
output;
term="EDGE IN"; role="Verb";
output;
term="EGG ON"; role="Verb";
output;
term="EN BLOC"; role="Adv";
output;
term="EN MASSE"; role="Adv";
output;
term="EN ROUTE"; role="Adv";
output;
term="ET AL."; role="Abbr";
output;
term="ET CETERA"; role="Adv";
output;
term="EVEN IF"; role="Conj";
output;
term="EVEN THOUGH"; role="Conj";
output;
term="EVER EXPANDING"; role="Adj";
output;
term="EX OFFICIO"; role="Adj";
output;
term="EX OFFICIO"; role="Adv";
output;
term="EX PARTE"; role="Adj";
output;
term="EX PARTE"; role="Adv";
output;
term="EXCEPT FOR"; role="Prep";
output;
term="EXCLUSIVE OF"; role="Prep";
output;
term="East German"; role="Adj";
output;
term="Edge In"; role="Verb";
output;
term="Egg On"; role="Verb";
output;
term="En Bloc"; role="Adv";
output;
term="En Masse"; role="Adv";
output;
term="En Route"; role="Adv";
output;
term="Et Al."; role="Abbr";
output;
term="Et Cetera"; role="Adv";
output;
term="Even If"; role="Conj";
output;
term="Even Though"; role="Conj";
output;
term="Ever Expanding"; role="Adj";
output;
term="Ex Officio"; role="Adj";
output;
term="Ex Officio"; role="Adv";
output;
term="Ex Parte"; role="Adj";
output;
term="Ex Parte"; role="Adv";
output;
term="Except For"; role="Prep";
output;
term="Exclusive Of"; role="Prep";
output;
term="FALL AWAY"; role="Verb";
output;
term="FALL BACK"; role="Verb";
output;
term="FILL IN"; role="Verb";
output;
term="FILLED UP"; role="Adj";
output;
term="FIND OUT"; role="Verb";
output;
term="FINE TUNE"; role="Verb";
output;
term="FIT IN"; role="Verb";
output;
term="FOR ALL THAT"; role="Conj";
output;
term="FOR SAKE OF"; role="Prep";
output;
term="FOR THE SAKE OF"; role="Prep";
output;
term="FOR WANT OF"; role="Prep";
output;
term="Fall Away"; role="Verb";
output;
term="Fall Back"; role="Verb";
output;
term="Fill In"; role="Verb";
output;
term="Filled Up"; role="Adj";
output;
term="Find Out"; role="Verb";
output;
term="Fine Tune"; role="Verb";
output;
term="Fit In"; role="Verb";
output;
term="For All That"; role="Conj";
output;
term="For Sake Of"; role="Prep";
output;
term="For The Sake Of"; role="Prep";
output;
term="For Want Of"; role="Prep";
output;
term="GIVE AWAY"; role="Verb";
output;
term="GIVE IN"; role="Verb";
output;
term="GIVE UP"; role="Verb";
output;
term="GIVEN THAT"; role="Conj";
output;
term="GO AHEAD"; role="Verb";
output;
term="GRANTING THAT"; role="Conj";
output;
term="GREAT DEAL"; role="Adv";
output;
term="GROW UP"; role="Verb";
output;
term="Give Away"; role="Verb";
output;
term="Give In"; role="Verb";
output;
term="Give Up"; role="Verb";
output;
term="Given That"; role="Conj";
output;
term="Go Ahead"; role="Verb";
output;
term="Granting That"; role="Conj";
output;
term="Great Deal"; role="Adv";
output;
term="Grow Up"; role="Verb";
output;
term="HAND OUT"; role="Verb";
output;
term="HAND OVER"; role="Verb";
output;
term="HIGH INCOME"; role="Adj";
output;
term="HIGH QUALITY"; role="Adj";
output;
term="HOLD BACK"; role="Verb";
output;
term="HOLD UP"; role="Verb";
output;
term="HOPED FOR"; role="Adj";
output;
term="HOW MANY"; role="Pron";
output;
term="HOW MUCH"; role="Pron";
output;
term="Hand Out"; role="Verb";
output;
term="Hand Over"; role="Verb";
output;
term="High Income"; role="Adj";
output;
term="High Quality"; role="Adj";
output;
term="Hold Back"; role="Verb";
output;
term="Hold Up"; role="Verb";
output;
term="Hoped For"; role="Adj";
output;
term="How Many"; role="Pron";
output;
term="How Much"; role="Pron";
output;
term="IN ABSENTIA"; role="Adv";
output;
term="IN ACCORDANCE WITH"; role="Prep";
output;
term="IN ADDITION"; role="Adv";
output;
term="IN ADDITION TO"; role="Prep";
output;
term="IN AID OF"; role="Prep";
output;
term="IN CASE"; role="Conj";
output;
term="IN CASE OF"; role="Prep";
output;
term="IN CHARGE OF"; role="Prep";
output;
term="IN COMMON WITH"; role="Prep";
output;
term="IN COMPARISON WITH"; role="Prep";
output;
term="IN COMPLIANCE WITH"; role="Prep";
output;
term="IN CONFORMITY WITH"; role="Prep";
output;
term="IN CONSEQUENCE OF"; role="Prep";
output;
term="IN CONTACT WITH"; role="Prep";
output;
term="IN EXCHANGE FOR"; role="Prep";
output;
term="IN FAVOUR OF"; role="Prep";
output;
term="IN FRONT"; role="Adv";
output;
term="IN FRONT OF"; role="Prep";
output;
term="IN GENERAL"; role="Adv";
output;
term="IN HEAT"; role="Adv";
output;
term="IN LIEU OF"; role="Prep";
output;
term="IN LIGHT OF"; role="Prep";
output;
term="IN LINE WITH"; role="Prep";
output;
term="IN NEED OF"; role="Prep";
output;
term="IN ORDER FOR"; role="Conj";
output;
term="IN ORDER THAT"; role="Conj";
output;
term="IN PARTICULAR"; role="Adv";
output;
term="IN PLACE OF"; role="Prep";
output;
term="IN POSITION"; role="Adv";
output;
term="IN PROCESS OF"; role="Prep";
output;
term="IN PURSUIT"; role="Adv";
output;
term="IN RE"; role="Prep";
output;
term="IN REFERENCE TO"; role="Prep";
output;
term="IN REGARD TO"; role="Prep";
output;
term="IN RELATION TO"; role="Prep";
output;
term="IN RESPECT OF"; role="Prep";
output;
term="IN RESPECT TO"; role="Prep";
output;
term="IN RETURN OF"; role="Prep";
output;
term="IN SEARCH OF"; role="Prep";
output;
term="IN SITU"; role="Adj";
output;
term="IN SITU"; role="Adv";
output;
term="IN SPITE OF"; role="Prep";
output;
term="IN THAT"; role="Conj";
output;
term="IN THE EVENT THAT"; role="Conj";
output;
term="IN THE FACE OF"; role="Prep";
output;
term="IN THE INTERIM"; role="Adv";
output;
term="IN THE INTERVAL"; role="Adv";
output;
term="IN THE LIGHT OF"; role="Prep";
output;
term="IN THE PROCESS OF"; role="Prep";
output;
term="IN THE RAW"; role="Adv";
output;
term="IN USE"; role="Adv";
output;
term="IN VACUO"; role="Adv";
output;
term="IN VIEW OF"; role="Prep";
output;
term="IN VITRO"; role="Adj";
output;
term="IN VITRO"; role="Adv";
output;
term="INASMUCH AS"; role="Conj";
output;
term="INSIDE OF"; role="Prep";
output;
term="INSOFAR AS"; role="Conj";
output;
term="INSOFAR THAT"; role="Conj";
output;
term="INSTEAD OF"; role="Prep";
output;
term="INTER ALIA"; role="Adv";
output;
term="IPSO FACTO"; role="Adv";
output;
term="IRRESPECTIVE OF"; role="Prep";
output;
term="In Absentia"; role="Adv";
output;
term="In Accordance With"; role="Prep";
output;
term="In Addition"; role="Adv";
output;
term="In Addition To"; role="Prep";
output;
term="In Aid Of"; role="Prep";
output;
term="In Case"; role="Conj";
output;
term="In Case Of"; role="Prep";
output;
term="In Charge Of"; role="Prep";
output;
term="In Common With"; role="Prep";
output;
term="In Comparison With"; role="Prep";
output;
term="In Compliance With"; role="Prep";
output;
term="In Conformity With"; role="Prep";
output;
term="In Consequence Of"; role="Prep";
output;
term="In Contact With"; role="Prep";
output;
term="In Exchange For"; role="Prep";
output;
term="In Favour Of"; role="Prep";
output;
term="In Front"; role="Adv";
output;
term="In Front Of"; role="Prep";
output;
term="In General"; role="Adv";
output;
term="In Heat"; role="Adv";
output;
term="In Lieu Of"; role="Prep";
output;
term="In Light Of"; role="Prep";
output;
term="In Line With"; role="Prep";
output;
term="In Need Of"; role="Prep";
output;
term="In Order For"; role="Conj";
output;
term="In Order That"; role="Conj";
output;
term="In Particular"; role="Adv";
output;
term="In Place Of"; role="Prep";
output;
term="In Position"; role="Adv";
output;
term="In Process Of"; role="Prep";
output;
term="In Pursuit"; role="Adv";
output;
term="In Re"; role="Prep";
output;
term="In Reference To"; role="Prep";
output;
term="In Regard To"; role="Prep";
output;
term="In Relation To"; role="Prep";
output;
term="In Respect Of"; role="Prep";
output;
term="In Respect To"; role="Prep";
output;
term="In Return Of"; role="Prep";
output;
term="In Search Of"; role="Prep";
output;
term="In Situ"; role="Adj";
output;
term="In Situ"; role="Adv";
output;
term="In Spite Of"; role="Prep";
output;
term="In That"; role="Conj";
output;
term="In The Event That"; role="Conj";
output;
term="In The Face Of"; role="Prep";
output;
term="In The Interim"; role="Adv";
output;
term="In The Interval"; role="Adv";
output;
term="In The Light Of"; role="Prep";
output;
term="In The Process Of"; role="Prep";
output;
term="In The Raw"; role="Adv";
output;
term="In Use"; role="Adv";
output;
term="In Vacuo"; role="Adv";
output;
term="In View Of"; role="Prep";
output;
term="In Vitro"; role="Adj";
output;
term="In Vitro"; role="Adv";
output;
term="Inasmuch As"; role="Conj";
output;
term="Inside Of"; role="Prep";
output;
term="Insofar As"; role="Conj";
output;
term="Insofar That"; role="Conj";
output;
term="Instead Of"; role="Prep";
output;
term="Inter Alia"; role="Adv";
output;
term="Ipso Facto"; role="Adv";
output;
term="Irrespective Of"; role="Prep";
output;
term="JUST ABOUT"; role="Adv";
output;
term="Just About"; role="Adv";
output;
term="KEEP IN MIND"; role="Verb";
output;
term="KEEP OUT"; role="Verb";
output;
term="KEEP UP"; role="Verb";
output;
term="KICK OFF"; role="Verb";
output;
term="Keep In Mind"; role="Verb";
output;
term="Keep Out"; role="Verb";
output;
term="Keep Up"; role="Verb";
output;
term="Kick Off"; role="Verb";
output;
term="LAID BACK"; role="Adj";
output;
term="LARGE SCALE"; role="Adj";
output;
term="LATIN AMERICAN"; role="Adj";
output;
term="LAY OUT"; role="Verb";
output;
term="LEAD ON"; role="Verb";
output;
term="LEAD TO"; role="Verb";
output;
term="LEAVE OUT"; role="Verb";
output;
term="LIGHT UP"; role="Verb";
output;
term="LINE UP"; role="Verb";
output;
term="LOCK UP"; role="Verb";
output;
term="LONG TIME"; role="Adj";
output;
term="LOOK FORWARD TO"; role="Verb";
output;
term="LOOK OUT"; role="Verb";
output;
term="LOW INCOME"; role="Adj";
output;
term="LOW LEVEL"; role="Adj";
output;
term="LOWER THAN"; role="Prep";
output;
term="Laid Back"; role="Adj";
output;
term="Large Scale"; role="Adj";
output;
term="Latin American"; role="Adj";
output;
term="Lay Out"; role="Verb";
output;
term="Lead On"; role="Verb";
output;
term="Lead To"; role="Verb";
output;
term="Leave Out"; role="Verb";
output;
term="Light Up"; role="Verb";
output;
term="Line Up"; role="Verb";
output;
term="Lock Up"; role="Verb";
output;
term="Long Time"; role="Adj";
output;
term="Look Forward To"; role="Verb";
output;
term="Look Out"; role="Verb";
output;
term="Low Income"; role="Adj";
output;
term="Low Level"; role="Adj";
output;
term="Lower Than"; role="Prep";
output;
term="MAKE OUT"; role="Verb";
output;
term="MAKE UP"; role="Verb";
output;
term="MARKET DRIVEN"; role="Adj";
output;
term="MENTALLY ILL"; role="Adj";
output;
term="MIX UP"; role="Verb";
output;
term="MIXED UP"; role="Adj";
output;
term="MORE OR LESS"; role="Adv";
output;
term="MOST OFTEN"; role="Adj";
output;
term="MOST REMOTE"; role="Adj";
output;
term="MOVE ALONG"; role="Verb";
output;
term="MUST DO"; role="Adj";
output;
term="Make Out"; role="Verb";
output;
term="Make Up"; role="Verb";
output;
term="Market Driven"; role="Adj";
output;
term="Mentally Ill"; role="Adj";
output;
term="Mix Up"; role="Verb";
output;
term="Mixed Up"; role="Adj";
output;
term="More Or Less"; role="Adv";
output;
term="Most Often"; role="Adj";
output;
term="Most Remote"; role="Adj";
output;
term="Move Along"; role="Verb";
output;
term="Must Do"; role="Adj";
output;
term="NEAR TO"; role="Prep";
output;
term="NEED TO"; role="Aux";
output;
term="NEEDS TO"; role="Aux";
output;
term="NETHERLANDS ANTILLEAN"; role="Adj";
output;
term="NEXT DAY"; role="Adj";
output;
term="NEXT TO"; role="Noun";
output;
term="NEXT TO"; role="Prep";
output;
term="NO ONE"; role="Pron";
output;
term="NORTH AMERICAN"; role="Adj";
output;
term="NORTH KOREAN"; role="Adj";
output;
term="NORTHERN IRISH"; role="Adj";
output;
term="NOT AS GOOD"; role="Adj";
output;
term="NOT FOR PROFIT"; role="Adj";
output;
term="NOT MANY"; role="Adj";
output;
term="NOT QUITE"; role="Adv";
output;
term="NOW AND THEN"; role="Adv";
output;
term="NOW THAT"; role="Conj";
output;
term="NULL AND VOID"; role="Adj";
output;
term="NUMBER ONE"; role="Adj";
output;
term="Near To"; role="Prep";
output;
term="Need To"; role="Aux";
output;
term="Needs To"; role="Aux";
output;
term="Netherlands Antillean"; role="Adj";
output;
term="Next Day"; role="Adj";
output;
term="Next To"; role="Noun";
output;
term="Next To"; role="Prep";
output;
term="No One"; role="Pron";
output;
term="North American"; role="Adj";
output;
term="North Korean"; role="Adj";
output;
term="Northern Irish"; role="Adj";
output;
term="Not As Good"; role="Adj";
output;
term="Not For Profit"; role="Adj";
output;
term="Not Many"; role="Adj";
output;
term="Not Quite"; role="Adv";
output;
term="Now And Then"; role="Adv";
output;
term="Now That"; role="Conj";
output;
term="Null And Void"; role="Adj";
output;
term="Number One"; role="Adj";
output;
term="OF LATE"; role="Adj";
output;
term="OFF OF"; role="Prep";
output;
term="OFF THE SHELF"; role="Adj";
output;
term="OLD FASHIONED"; role="Adj";
output;
term="ON ACCOUNT OF"; role="Prep";
output;
term="ON ALL SIDES"; role="Adv";
output;
term="ON BEHALF OF"; role="Prep";
output;
term="ON GROUNDS OF"; role="Prep";
output;
term="ON HOLD"; role="Adv";
output;
term="ON PAIN OF"; role="Prep";
output;
term="ON THE GROUNDS OF"; role="Prep";
output;
term="ON THE MATTER OF"; role="Prep";
output;
term="ON THE PART OF"; role="Prep";
output;
term="ON THE STRENGTH OF"; role="Prep";
output;
term="ON TIME"; role="Adv";
output;
term="ON TO"; role="Prep";
output;
term="ON TOP OF"; role="Prep";
output;
term="ONCE MORE"; role="Adv";
output;
term="ONE MORE"; role="Adv";
output;
term="OP CIT."; role="Abbr";
output;
term="OUGHT TO"; role="Aux";
output;
term="OUT OF"; role="Noun";
output;
term="OUT OF"; role="Prep";
output;
term="OUT OF CONTROL"; role="Adj";
output;
term="OUT OF WORK"; role="Adj";
output;
term="OUTSIDE OF"; role="Prep";
output;
term="OWING TO"; role="Prep";
output;
term="Of Late"; role="Adj";
output;
term="Off Of"; role="Prep";
output;
term="Off The Shelf"; role="Adj";
output;
term="Old Fashioned"; role="Adj";
output;
term="On Account Of"; role="Prep";
output;
term="On All Sides"; role="Adv";
output;
term="On Behalf Of"; role="Prep";
output;
term="On Grounds Of"; role="Prep";
output;
term="On Hold"; role="Adv";
output;
term="On Pain Of"; role="Prep";
output;
term="On The Grounds Of"; role="Prep";
output;
term="On The Matter Of"; role="Prep";
output;
term="On The Part Of"; role="Prep";
output;
term="On The Strength Of"; role="Prep";
output;
term="On Time"; role="Adv";
output;
term="On To"; role="Prep";
output;
term="On Top Of"; role="Prep";
output;
term="Once More"; role="Adv";
output;
term="One More"; role="Adv";
output;
term="Op Cit."; role="Abbr";
output;
term="Ought To"; role="Aux";
output;
term="Out Of"; role="Noun";
output;
term="Out Of"; role="Prep";
output;
term="Out Of Control"; role="Adj";
output;
term="Out Of Work"; role="Adj";
output;
term="Outside Of"; role="Prep";
output;
term="Owing To"; role="Prep";
output;
term="PAPER BASED"; role="Adj";
output;
term="PAR EXCELLENCE"; role="Adj";
output;
term="PAR EXCELLENCE"; role="Adv";
output;
term="PARI PASSU"; role="Adj";
output;
term="PAY UP"; role="Verb";
output;
term="PER ANNUM"; role="Adv";
output;
term="PER CAPITA"; role="Adj";
output;
term="PER CAPITA"; role="Adv";
output;
term="PER DIEM"; role="Adj";
output;
term="PER DIEM"; role="Adv";
output;
term="PER SE"; role="Adv";
output;
term="PICK UP"; role="Verb";
output;
term="PLAY DOWN"; role="Verb";
output;
term="POINT OUT"; role="Verb";
output;
term="PRELIMINARY TO"; role="Prep";
output;
term="PREPARATORY TO"; role="Prep";
output;
term="PREVIOUS TO"; role="Prep";
output;
term="PRIMA FACIE"; role="Adj";
output;
term="PRIMA FACIE"; role="Adv";
output;
term="PRIOR TO"; role="Prep";
output;
term="PRO FORMA"; role="Adj";
output;
term="PRO FORMA"; role="Adv";
output;
term="PRO RATA"; role="Adv";
output;
term="PROVIDED THAT"; role="Conj";
output;
term="PROVIDING THAT"; role="Conj";
output;
term="PURSUANT TO"; role="Prep";
output;
term="PUT BY"; role="Verb";
output;
term="PUT DOWN"; role="Verb";
output;
term="PUT FORTH"; role="Verb";
output;
term="PUT OFF"; role="Verb";
output;
term="PUT ON"; role="Verb";
output;
term="PUT OUT"; role="Verb";
output;
term="PUT UP"; role="Verb";
output;
term="Paper Based"; role="Adj";
output;
term="Par Excellence"; role="Adj";
output;
term="Par Excellence"; role="Adv";
output;
term="Pari Passu"; role="Adj";
output;
term="Pay Up"; role="Verb";
output;
term="Per Annum"; role="Adv";
output;
term="Per Capita"; role="Adj";
output;
term="Per Capita"; role="Adv";
output;
term="Per Diem"; role="Adj";
output;
term="Per Diem"; role="Adv";
output;
term="Per Se"; role="Adv";
output;
term="Pick Up"; role="Verb";
output;
term="Play Down"; role="Verb";
output;
term="Point Out"; role="Verb";
output;
term="Preliminary To"; role="Prep";
output;
term="Preparatory To"; role="Prep";
output;
term="Previous To"; role="Prep";
output;
term="Prima Facie"; role="Adj";
output;
term="Prima Facie"; role="Adv";
output;
term="Prior To"; role="Prep";
output;
term="Pro Forma"; role="Adj";
output;
term="Pro Forma"; role="Adv";
output;
term="Pro Rata"; role="Adv";
output;
term="Provided That"; role="Conj";
output;
term="Providing That"; role="Conj";
output;
term="Pursuant To"; role="Prep";
output;
term="Put By"; role="Verb";
output;
term="Put Down"; role="Verb";
output;
term="Put Forth"; role="Verb";
output;
term="Put Off"; role="Verb";
output;
term="Put On"; role="Verb";
output;
term="Put Out"; role="Verb";
output;
term="Put Up"; role="Verb";
output;
term="REGARDLESS OF"; role="Prep";
output;
term="RELATIVE TO"; role="Prep";
output;
term="ROUND UP"; role="Verb";
output;
term="Regardless Of"; role="Prep";
output;
term="Relative To"; role="Prep";
output;
term="Round Up"; role="Verb";
output;
term="SAS INSTITUTE"; role="Noun";
output;
term="SAUDI ARABIAN"; role="Adj";
output;
term="SAVE THAT"; role="Conj";
output;
term="SECOND CLASS"; role="Adj";
output;
term="SECOND LEVEL"; role="Adj";
output;
term="SEEING THAT"; role="Conj";
output;
term="SET AT"; role="Verb";
output;
term="SET BACK"; role="Verb";
output;
term="SET OFF"; role="Verb";
output;
term="SET ON"; role="Verb";
output;
term="SET OUT"; role="Verb";
output;
term="SET UP"; role="Verb";
output;
term="SHOW UP"; role="Verb";
output;
term="SIDE BY SIDE"; role="Adj";
output;
term="SIDE BY SIDE"; role="Adv";
output;
term="SIGN UP"; role="Verb";
output;
term="SINE DIE"; role="Adv";
output;
term="SINGLE OUT"; role="Verb";
output;
term="SO AS"; role="Conj";
output;
term="SO LONG"; role="Interj";
output;
term="SO THAT"; role="Conj";
output;
term="SOAK UP"; role="Verb";
output;
term="SOUGHT AFTER"; role="Adj";
output;
term="SOUTH AFRICAN"; role="Adj";
output;
term="SOUTH AMERICAN"; role="Adj";
output;
term="SOUTH KOREAN"; role="Adj";
output;
term="SOUTHEAST ASIAN"; role="Adj";
output;
term="SPELL OUT"; role="Verb";
output;
term="SRI LANKAN"; role="Adj";
output;
term="STAMP OUT"; role="Verb";
output;
term="STAND OUT"; role="Verb";
output;
term="STAND UP"; role="Verb";
output;
term="STEMMING FROM"; role="Prep";
output;
term="STEP UP"; role="Verb";
output;
term="SUB JUDICE"; role="Adv";
output;
term="SUBSEQUENT TO"; role="Prep";
output;
term="SUCH AS"; role="Prep";
output;
term="SUCH THAT"; role="Conj";
output;
term="SUI GENERIS"; role="Adj";
output;
term="Sas Institute"; role="Noun";
output;
term="Saudi Arabian"; role="Adj";
output;
term="Save That"; role="Conj";
output;
term="Second Class"; role="Adj";
output;
term="Second Level"; role="Adj";
output;
term="Seeing That"; role="Conj";
output;
term="Set At"; role="Verb";
output;
term="Set Back"; role="Verb";
output;
term="Set Off"; role="Verb";
output;
term="Set On"; role="Verb";
output;
term="Set Out"; role="Verb";
output;
term="Set Up"; role="Verb";
output;
term="Show Up"; role="Verb";
output;
term="Side By Side"; role="Adj";
output;
term="Side By Side"; role="Adv";
output;
term="Sign Up"; role="Verb";
output;
term="Sine Die"; role="Adv";
output;
term="Single Out"; role="Verb";
output;
term="So As"; role="Conj";
output;
term="So Long"; role="Interj";
output;
term="So That"; role="Conj";
output;
term="Soak Up"; role="Verb";
output;
term="Sought After"; role="Adj";
output;
term="South African"; role="Adj";
output;
term="South American"; role="Adj";
output;
term="South Korean"; role="Adj";
output;
term="Southeast Asian"; role="Adj";
output;
term="Spell Out"; role="Verb";
output;
term="Sri Lankan"; role="Adj";
output;
term="Stamp Out"; role="Verb";
output;
term="Stand Out"; role="Verb";
output;
term="Stand Up"; role="Verb";
output;
term="Stemming From"; role="Prep";
output;
term="Step Up"; role="Verb";
output;
term="Sub Judice"; role="Adv";
output;
term="Subsequent To"; role="Prep";
output;
term="Such As"; role="Prep";
output;
term="Such That"; role="Conj";
output;
term="Sui Generis"; role="Adj";
output;
term="TAKE ADVANTAGE"; role="Verb";
output;
term="TAKE AWAY"; role="Verb";
output;
term="TAKE IN"; role="Verb";
output;
term="TAKE OFF"; role="Verb";
output;
term="TAKE ON"; role="Verb";
output;
term="TAKE OUT"; role="Verb";
output;
term="TAKE OVER"; role="Verb";
output;
term="TAKE PLACE"; role="Verb";
output;
term="TAKE UP"; role="Verb";
output;
term="THANK YOU"; role="Interj";
output;
term="THANKS TO"; role="Prep";
output;
term="THIRD DEGREE"; role="Adj";
output;
term="THIRD PARTY"; role="Adj";
output;
term="TIE UP"; role="Verb";
output;
term="TIP OVER"; role="Verb";
output;
term="TO A DEGREE"; role="Adv";
output;
term="TO THE POINT"; role="Adj";
output;
term="TOGETHER WITH"; role="Prep";
output;
term="TOO SOON"; role="Adv";
output;
term="TURN DOWN"; role="Verb";
output;
term="TURN IN"; role="Verb";
output;
term="TURN ON"; role="Verb";
output;
term="TURN OUT"; role="Verb";
output;
term="TURN OVER"; role="Verb";
output;
term="TURNED ON"; role="Adj";
output;
term="Take Advantage"; role="Verb";
output;
term="Take Away"; role="Verb";
output;
term="Take In"; role="Verb";
output;
term="Take Off"; role="Verb";
output;
term="Take On"; role="Verb";
output;
term="Take Out"; role="Verb";
output;
term="Take Over"; role="Verb";
output;
term="Take Place"; role="Verb";
output;
term="Take Up"; role="Verb";
output;
term="Thank You"; role="Interj";
output;
term="Thanks To"; role="Prep";
output;
term="Third Degree"; role="Adj";
output;
term="Third Party"; role="Adj";
output;
term="Tie Up"; role="Verb";
output;
term="Tip Over"; role="Verb";
output;
term="To A Degree"; role="Adv";
output;
term="To The Point"; role="Adj";
output;
term="Together With"; role="Prep";
output;
term="Too Soon"; role="Adv";
output;
term="Turn Down"; role="Verb";
output;
term="Turn In"; role="Verb";
output;
term="Turn On"; role="Verb";
output;
term="Turn Out"; role="Verb";
output;
term="Turn Over"; role="Verb";
output;
term="Turned On"; role="Adj";
output;
term="ULTRA VIRES"; role="Adv";
output;
term="UNDER WAY"; role="Adv";
output;
term="UP AGAINST"; role="Prep";
output;
term="UP TO"; role="Prep";
output;
term="UPSIDE DOWN"; role="Adv";
output;
term="UPWARDS OF"; role="Prep";
output;
term="USE UP"; role="Verb";
output;
term="USED TO"; role="Aux";
output;
term="Ultra Vires"; role="Adv";
output;
term="Under Way"; role="Adv";
output;
term="Up Against"; role="Prep";
output;
term="Up To"; role="Prep";
output;
term="Upside Down"; role="Adv";
output;
term="Upwards Of"; role="Prep";
output;
term="Use Up"; role="Verb";
output;
term="Used To"; role="Aux";
output;
term="VICE VERSA"; role="Adv";
output;
term="Vice Versa"; role="Adv";
output;
term="WARD OFF"; role="Verb";
output;
term="WARM BLOODED"; role="Adj";
output;
term="WASTE AWAY"; role="Verb";
output;
term="WEAR OUT"; role="Verb";
output;
term="WELL KNOWN"; role="Adj";
output;
term="WIND UP"; role="Verb";
output;
term="WIPE OUT"; role="Verb";
output;
term="WITH REFERENCE TO"; role="Prep";
output;
term="WITH REGARD TO"; role="Prep";
output;
term="WITH RESPECT TO"; role="Prep";
output;
term="WITH THE EXCEPTION OF"; role="Prep";
output;
term="WITHIN REACH"; role="Adj";
output;
term="WITHOUT DOUBT"; role="Adj";
output;
term="WORK OUT"; role="Verb";
output;
term="WRAPPED UP"; role="Adj";
output;
term="WRITE DOWN"; role="Verb";
output;
term="Ward Off"; role="Verb";
output;
term="Warm Blooded"; role="Adj";
output;
term="Waste Away"; role="Verb";
output;
term="Wear Out"; role="Verb";
output;
term="Well Known"; role="Adj";
output;
term="Wind Up"; role="Verb";
output;
term="Wipe Out"; role="Verb";
output;
term="With Reference To"; role="Prep";
output;
term="With Regard To"; role="Prep";
output;
term="With Respect To"; role="Prep";
output;
term="With The Exception Of"; role="Prep";
output;
term="Within Reach"; role="Adj";
output;
term="Without Doubt"; role="Adj";
output;
term="Work Out"; role="Verb";
output;
term="Wrapped Up"; role="Adj";
output;
term="Write Down"; role="Verb";
output;
term="ZERO IN"; role="Verb";
output;
term="Zero In"; role="Verb";
output;
term="a bit"; role="Adv";
output;
term="a fortiori"; role="Adv";
output;
term="a lot"; role="Adv";
output;
term="a lot of"; role="Adj";
output;
term="a posteriori"; role="Adj";
output;
term="a posteriori"; role="Adv";
output;
term="a priori"; role="Adj";
output;
term="a priori"; role="Adv";
output;
term="according to"; role="Prep";
output;
term="ad hoc"; role="Adj";
output;
term="ad interim"; role="Adv";
output;
term="ahead of"; role="Prep";
output;
term="all the time"; role="Adv";
output;
term="along with"; role="Prep";
output;
term="any moment"; role="Adv";
output;
term="any second"; role="Adv";
output;
term="apart from"; role="Prep";
output;
term="as a result of"; role="Prep";
output;
term="as a rule"; role="Adv";
output;
term="as far as"; role="Conj";
output;
term="as far as"; role="Prep";
output;
term="as for"; role="Prep";
output;
term="as if"; role="Conj";
output;
term="as in"; role="Prep";
output;
term="as long as"; role="Conj";
output;
term="as many as"; role="Adv";
output;
term="as of"; role="Prep";
output;
term="as one"; role="Adv";
output;
term="as per"; role="Prep";
output;
term="as regards"; role="Prep";
output;
term="as soon as"; role="Conj";
output;
term="as though"; role="Conj";
output;
term="as to"; role="Prep";
output;
term="as well"; role="Adv";
output;
term="as well as"; role="Conj";
output;
term="as yet"; role="Adv";
output;
term="aside from"; role="Prep";
output;
term="assuming that"; role="Conj";
output;
term="at all"; role="Adv";
output;
term="at any rate"; role="Adv";
output;
term="at least one"; role="Adj";
output;
term="at once"; role="Adv";
output;
term="at the expense of"; role="Prep";
output;
term="at variance with"; role="Prep";
output;
term="away from"; role="Prep";
output;
term="back of"; role="Prep";
output;
term="bear up"; role="Verb";
output;
term="because of"; role="Prep";
output;
term="best known"; role="Adj";
output;
term="black and white"; role="Adj";
output;
term="bona fide"; role="Adj";
output;
term="break up"; role="Verb";
output;
term="bring about"; role="Verb";
output;
term="bring up"; role="Verb";
output;
term="build up"; role="Verb";
output;
term="but for"; role="Prep";
output;
term="by dint of"; role="Prep";
output;
term="by itself"; role="Adv";
output;
term="by means of"; role="Prep";
output;
term="by proxy"; role="Adv";
output;
term="by reason of"; role="Prep";
output;
term="by the way"; role="Adv";
output;
term="by virtue of"; role="Prep";
output;
term="by way of"; role="Prep";
output;
term="carry on"; role="Verb";
output;
term="carry out"; role="Verb";
output;
term="carry through"; role="Verb";
output;
term="catch on"; role="Verb";
output;
term="central african"; role="Adj";
output;
term="clean up"; role="Verb";
output;
term="clear up"; role="Verb";
output;
term="close by"; role="Adv";
output;
term="close to"; role="Adv";
output;
term="come about"; role="Verb";
output;
term="come in"; role="Verb";
output;
term="come on"; role="Verb";
output;
term="considering that"; role="Conj";
output;
term="costa rican"; role="Adj";
output;
term="cover up"; role="Verb";
output;
term="cut off"; role="Verb";
output;
term="dare to"; role="Aux";
output;
term="dark blue"; role="Adj";
output;
term="de facto"; role="Adj";
output;
term="de facto"; role="Adv";
output;
term="de jure"; role="Adj";
output;
term="de jure"; role="Adv";
output;
term="devoid of"; role="Prep";
output;
term="draw down"; role="Verb";
output;
term="due to"; role="Prep";
output;
term="east german"; role="Adj";
output;
term="edge in"; role="Verb";
output;
term="egg on"; role="Verb";
output;
term="en bloc"; role="Adv";
output;
term="en masse"; role="Adv";
output;
term="en route"; role="Adv";
output;
term="et al."; role="Abbr";
output;
term="et cetera"; role="Adv";
output;
term="even if"; role="Conj";
output;
term="even though"; role="Conj";
output;
term="ever expanding"; role="Adj";
output;
term="ex officio"; role="Adj";
output;
term="ex officio"; role="Adv";
output;
term="ex parte"; role="Adj";
output;
term="ex parte"; role="Adv";
output;
term="except for"; role="Prep";
output;
term="exclusive of"; role="Prep";
output;
term="fall away"; role="Verb";
output;
term="fall back"; role="Verb";
output;
term="fill in"; role="Verb";
output;
term="filled up"; role="Adj";
output;
term="find out"; role="Verb";
output;
term="fine tune"; role="Verb";
output;
term="fit in"; role="Verb";
output;
term="for all that"; role="Conj";
output;
term="for sake of"; role="Prep";
output;
term="for the sake of"; role="Prep";
output;
term="for want of"; role="Prep";
output;
term="give away"; role="Verb";
output;
term="give in"; role="Verb";
output;
term="give up"; role="Verb";
output;
term="given that"; role="Conj";
output;
term="go ahead"; role="Verb";
output;
term="granting that"; role="Conj";
output;
term="great deal"; role="Adv";
output;
term="grow up"; role="Verb";
output;
term="hand out"; role="Verb";
output;
term="hand over"; role="Verb";
output;
term="high income"; role="Adj";
output;
term="high quality"; role="Adj";
output;
term="hold back"; role="Verb";
output;
term="hold up"; role="Verb";
output;
term="hoped for"; role="Adj";
output;
term="how many"; role="Pron";
output;
term="how much"; role="Pron";
output;
term="in absentia"; role="Adv";
output;
term="in accordance with"; role="Prep";
output;
term="in addition"; role="Adv";
output;
term="in addition to"; role="Prep";
output;
term="in aid of"; role="Prep";
output;
term="in case"; role="Conj";
output;
term="in case of"; role="Prep";
output;
term="in charge of"; role="Prep";
output;
term="in common with"; role="Prep";
output;
term="in comparison with"; role="Prep";
output;
term="in compliance with"; role="Prep";
output;
term="in conformity with"; role="Prep";
output;
term="in consequence of"; role="Prep";
output;
term="in contact with"; role="Prep";
output;
term="in exchange for"; role="Prep";
output;
term="in favour of"; role="Prep";
output;
term="in front"; role="Adv";
output;
term="in front of"; role="Prep";
output;
term="in general"; role="Adv";
output;
term="in heat"; role="Adv";
output;
term="in lieu of"; role="Prep";
output;
term="in light of"; role="Prep";
output;
term="in line with"; role="Prep";
output;
term="in need of"; role="Prep";
output;
term="in order for"; role="Conj";
output;
term="in order that"; role="Conj";
output;
term="in particular"; role="Adv";
output;
term="in place of"; role="Prep";
output;
term="in position"; role="Adv";
output;
term="in process of"; role="Prep";
output;
term="in pursuit"; role="Adv";
output;
term="in re"; role="Prep";
output;
term="in reference to"; role="Prep";
output;
term="in regard to"; role="Prep";
output;
term="in relation to"; role="Prep";
output;
term="in respect of"; role="Prep";
output;
term="in respect to"; role="Prep";
output;
term="in return of"; role="Prep";
output;
term="in search of"; role="Prep";
output;
term="in situ"; role="Adj";
output;
term="in situ"; role="Adv";
output;
term="in spite of"; role="Prep";
output;
term="in that"; role="Conj";
output;
term="in the event that"; role="Conj";
output;
term="in the face of"; role="Prep";
output;
term="in the interim"; role="Adv";
output;
term="in the interval"; role="Adv";
output;
term="in the light of"; role="Prep";
output;
term="in the process of"; role="Prep";
output;
term="in the raw"; role="Adv";
output;
term="in use"; role="Adv";
output;
term="in vacuo"; role="Adv";
output;
term="in view of"; role="Prep";
output;
term="in vitro"; role="Adj";
output;
term="in vitro"; role="Adv";
output;
term="inasmuch as"; role="Conj";
output;
term="inside of"; role="Prep";
output;
term="insofar as"; role="Conj";
output;
term="insofar that"; role="Conj";
output;
term="instead of"; role="Prep";
output;
term="inter alia"; role="Adv";
output;
term="ipso facto"; role="Adv";
output;
term="irrespective of"; role="Prep";
output;
term="just about"; role="Adv";
output;
term="keep in mind"; role="Verb";
output;
term="keep out"; role="Verb";
output;
term="keep up"; role="Verb";
output;
term="kick off"; role="Verb";
output;
term="laid back"; role="Adj";
output;
term="large scale"; role="Adj";
output;
term="latin american"; role="Adj";
output;
term="lay out"; role="Verb";
output;
term="lead on"; role="Verb";
output;
term="lead to"; role="Verb";
output;
term="leave out"; role="Verb";
output;
term="light up"; role="Verb";
output;
term="line up"; role="Verb";
output;
term="lock up"; role="Verb";
output;
term="long time"; role="Adj";
output;
term="look forward to"; role="Verb";
output;
term="look out"; role="Verb";
output;
term="low income"; role="Adj";
output;
term="low level"; role="Adj";
output;
term="lower than"; role="Prep";
output;
term="make out"; role="Verb";
output;
term="make up"; role="Verb";
output;
term="market driven"; role="Adj";
output;
term="mentally ill"; role="Adj";
output;
term="mix up"; role="Verb";
output;
term="mixed up"; role="Adj";
output;
term="more or less"; role="Adv";
output;
term="most often"; role="Adj";
output;
term="most remote"; role="Adj";
output;
term="move along"; role="Verb";
output;
term="must do"; role="Adj";
output;
term="near to"; role="Prep";
output;
term="need to"; role="Aux";
output;
term="needs to"; role="Aux";
output;
term="netherlands antillean"; role="Adj";
output;
term="next day"; role="Adj";
output;
term="next to"; role="Noun";
output;
term="next to"; role="Prep";
output;
term="no one"; role="Pron";
output;
term="north american"; role="Adj";
output;
term="north korean"; role="Adj";
output;
term="northern irish"; role="Adj";
output;
term="not as good"; role="Adj";
output;
term="not for profit"; role="Adj";
output;
term="not many"; role="Adj";
output;
term="not quite"; role="Adv";
output;
term="now and then"; role="Adv";
output;
term="now that"; role="Conj";
output;
term="null and void"; role="Adj";
output;
term="number one"; role="Adj";
output;
term="of late"; role="Adj";
output;
term="off of"; role="Prep";
output;
term="off the shelf"; role="Adj";
output;
term="old fashioned"; role="Adj";
output;
term="on account of"; role="Prep";
output;
term="on all sides"; role="Adv";
output;
term="on behalf of"; role="Prep";
output;
term="on grounds of"; role="Prep";
output;
term="on hold"; role="Adv";
output;
term="on pain of"; role="Prep";
output;
term="on the grounds of"; role="Prep";
output;
term="on the matter of"; role="Prep";
output;
term="on the part of"; role="Prep";
output;
term="on the strength of"; role="Prep";
output;
term="on time"; role="Adv";
output;
term="on to"; role="Prep";
output;
term="on top of"; role="Prep";
output;
term="once more"; role="Adv";
output;
term="one more"; role="Adv";
output;
term="op cit."; role="Abbr";
output;
term="ought to"; role="Aux";
output;
term="out of"; role="Noun";
output;
term="out of"; role="Prep";
output;
term="out of control"; role="Adj";
output;
term="out of work"; role="Adj";
output;
term="outside of"; role="Prep";
output;
term="owing to"; role="Prep";
output;
term="paper based"; role="Adj";
output;
term="par excellence"; role="Adj";
output;
term="par excellence"; role="Adv";
output;
term="pari passu"; role="Adj";
output;
term="pay up"; role="Verb";
output;
term="per annum"; role="Adv";
output;
term="per capita"; role="Adj";
output;
term="per capita"; role="Adv";
output;
term="per diem"; role="Adj";
output;
term="per diem"; role="Adv";
output;
term="per se"; role="Adv";
output;
term="pick up"; role="Verb";
output;
term="play down"; role="Verb";
output;
term="point out"; role="Verb";
output;
term="preliminary to"; role="Prep";
output;
term="preparatory to"; role="Prep";
output;
term="previous to"; role="Prep";
output;
term="prima facie"; role="Adj";
output;
term="prima facie"; role="Adv";
output;
term="prior to"; role="Prep";
output;
term="pro forma"; role="Adj";
output;
term="pro forma"; role="Adv";
output;
term="pro rata"; role="Adv";
output;
term="provided that"; role="Conj";
output;
term="providing that"; role="Conj";
output;
term="pursuant to"; role="Prep";
output;
term="put by"; role="Verb";
output;
term="put down"; role="Verb";
output;
term="put forth"; role="Verb";
output;
term="put off"; role="Verb";
output;
term="put on"; role="Verb";
output;
term="put out"; role="Verb";
output;
term="put up"; role="Verb";
output;
term="regardless of"; role="Prep";
output;
term="relative to"; role="Prep";
output;
term="round up"; role="Verb";
output;
term="sas institute"; role="Noun";
output;
term="saudi arabian"; role="Adj";
output;
term="save that"; role="Conj";
output;
term="second class"; role="Adj";
output;
term="second level"; role="Adj";
output;
term="seeing that"; role="Conj";
output;
term="set at"; role="Verb";
output;
term="set back"; role="Verb";
output;
term="set off"; role="Verb";
output;
term="set on"; role="Verb";
output;
term="set out"; role="Verb";
output;
term="set up"; role="Verb";
output;
term="show up"; role="Verb";
output;
term="side by side"; role="Adj";
output;
term="side by side"; role="Adv";
output;
term="sign up"; role="Verb";
output;
term="sine die"; role="Adv";
output;
term="single out"; role="Verb";
output;
term="so as"; role="Conj";
output;
term="so long"; role="Interj";
output;
term="so that"; role="Conj";
output;
term="soak up"; role="Verb";
output;
term="sought after"; role="Adj";
output;
term="south african"; role="Adj";
output;
term="south american"; role="Adj";
output;
term="south korean"; role="Adj";
output;
term="southeast asian"; role="Adj";
output;
term="spell out"; role="Verb";
output;
term="sri lankan"; role="Adj";
output;
term="stamp out"; role="Verb";
output;
term="stand out"; role="Verb";
output;
term="stand up"; role="Verb";
output;
term="stemming from"; role="Prep";
output;
term="step up"; role="Verb";
output;
term="sub judice"; role="Adv";
output;
term="subsequent to"; role="Prep";
output;
term="such as"; role="Prep";
output;
term="such that"; role="Conj";
output;
term="sui generis"; role="Adj";
output;
term="take advantage"; role="Verb";
output;
term="take away"; role="Verb";
output;
term="take in"; role="Verb";
output;
term="take off"; role="Verb";
output;
term="take on"; role="Verb";
output;
term="take out"; role="Verb";
output;
term="take over"; role="Verb";
output;
term="take place"; role="Verb";
output;
term="take up"; role="Verb";
output;
term="thank you"; role="Interj";
output;
term="thanks to"; role="Prep";
output;
term="third degree"; role="Adj";
output;
term="third party"; role="Adj";
output;
term="tie up"; role="Verb";
output;
term="tip over"; role="Verb";
output;
term="to a degree"; role="Adv";
output;
term="to the point"; role="Adj";
output;
term="together with"; role="Prep";
output;
term="too soon"; role="Adv";
output;
term="turn down"; role="Verb";
output;
term="turn in"; role="Verb";
output;
term="turn on"; role="Verb";
output;
term="turn out"; role="Verb";
output;
term="turn over"; role="Verb";
output;
term="turned on"; role="Adj";
output;
term="ultra vires"; role="Adv";
output;
term="under way"; role="Adv";
output;
term="up against"; role="Prep";
output;
term="up to"; role="Prep";
output;
term="upside down"; role="Adv";
output;
term="upwards of"; role="Prep";
output;
term="use up"; role="Verb";
output;
term="used to"; role="Aux";
output;
term="vice versa"; role="Adv";
output;
term="ward off"; role="Verb";
output;
term="warm blooded"; role="Adj";
output;
term="waste away"; role="Verb";
output;
term="wear out"; role="Verb";
output;
term="well known"; role="Adj";
output;
term="wind up"; role="Verb";
output;
term="wipe out"; role="Verb";
output;
term="with reference to"; role="Prep";
output;
term="with regard to"; role="Prep";
output;
term="with respect to"; role="Prep";
output;
term="with the exception of"; role="Prep";
output;
term="within reach"; role="Adj";
output;
term="without doubt"; role="Adj";
output;
term="work out"; role="Verb";
output;
term="wrapped up"; role="Adj";
output;
term="write down"; role="Verb";
output;
term="zero in"; role="Verb";
output;
;
run;
data TextFilter_config;
  length   cellwgt                          $  24
           termwgt                          $  24
           multiencoding                    $  24
           namedfile                        $   1
           language                         $  32
           encoding                         $  16
           plugin                           $  12
           stemming                         $   1
           tagging                          $   1
           NG                               $   3
           entities                         $   1
           entList                          $ 200
           attributes                       $   1
           attrList                         $ 200
           pos                              $   1
           posList                          $  43
           multiterm                        $ 114
           litilist                         $ 200
           parseVar                         $  32
           displayVar                       $   1
           targetvar                        $   1
           lastfilternode                   $  11
           lastparsenode                    $  11
           last_prescore                    $  43
           maxterms                             8
           mindocs                              8
           ;
 
cellwgt="LOG"; termwgt="ENTROPY"; multiencoding="windows-1252"; namedfile="N"; language="english"; encoding="wlatin1"; plugin="Teragram"; stemming="Y"; tagging="Y"; NG="STD"; entities="N";
entList=""; attributes="D"; attrList="NUM PUNCT"; pos="D"; posList="AUX CONJ DET INTERJ PART PREP PRON Newline";
multiterm="F:\Dropbox\NOVA\1st\DataMining\Project\DataMining\Songs\SAS_Miner\Songs\Workspaces\EMWS1\TextParsing\multiword.txt"; litilist=""; parseVar="song_name"; displayVar=""; targetvar="";
lastfilternode="TextParsing"; lastparsenode="TextParsing"; last_prescore="TextParsing"; maxterms=.; mindocs=4;
output;
;
run;

%let _multifile=%SYSFUNC(PATHNAME(work))/TextFilter_multi.txt;
%let _multiSLength= %klength(&_multifile);

data TextFilter_config;
length multiterm $ &_multiSLength;
set TextFilter_config;
multiterm=ktrim(symget('_multifile'));
run;

proc sql;
select multiencoding into: _tmmultiencoding
from TextFilter_config;
quit;

filename _multout "&_multifile";
data _NULL_;
set TextFilter_multiwordterms;
file _multout encoding= "%trim(&_tmmultiencoding)";
put term ':3:' role;
run;
